### ISSUE TITLE
如何使用fake-linker 对app网络流量重定向

### ISSUE THREAD

**Issue by fuqiangleon** [sanfengAndroid/fake-linker#3]
需求： 需将App 的流量强制重定向至socks5 代理

现状： 已实现了一个socket connect 函数的动态库，计划使用fake-linker 加载这个so，然后利用so 库将网络流量重定向

问题：参考文档，没有看明白如何使用已经实现好的so文件，或者是我对项目理解有误，麻烦指点下，谢谢。

**Comment by sanfengAndroid** [comment]
fake-linker本身是一个动态库,你只需要在app内合适的时机调用 FakeLinker.initFakeLinker https://github.com/sanfengAndroid/fake-linker/blob/acf0ecad8728732c21179886cd44ddbdcf194d3e/src/main/java/com/sanfengandroid/fakelinker/FakeLinker.java#L53
linkerPath 就是 fake-linker 的路径, hookModulePath 是你自身提供的包含 socket connect 的动态库路径,cacheDir 是提供内部临时文件写入的目录,需要保证权限能够读写,configPath可忽略, processName 当前进程名,调用成功后会将你提供的so变为全局库,这会影响在这之后的所有加载库的链接,会优先链接到你的库,值得注意的是你本身加载时机如果比较晚(包含socket connect的库已经加载了)则你需要在你的模块中手动调用 call_common_function 方法,api参考
https://github.com/sanfengAndroid/fake-linker/blob/acf0ecad8728732c21179886cd44ddbdcf194d3e/src/main/cpp/export/linker_export.h#L155-L173

**Comment by fuqiangleon** [comment]
1. so 变为全局库是指整个手机系统层面 还是app 自身请求范围？
2. call_common_function 方法是指继续使用系统默认而不是hook 过的方法吗？

**Comment by sanfengAndroid** [comment]
1. 刚才回答有问题,调用 FakeLinker.initFakeLinker 时会回调你的 hook 模块,你需要实现导出符号
https://github.com/sanfengAndroid/fake-linker/blob/acf0ecad8728732c21179886cd44ddbdcf194d3e/src/main/cpp/export/linker_export.h#L278-L288
fake-linker 加载成功会回调这个方法,然后根据你自己需要,将该模块变为 全局模块 具体的使用参考
https://github.com/sanfengAndroid/fake-linker/blob/main/README_CN.md 的使用示例
2. 全局库只是针对当前进程,普通app注入也就是只有app生效,只有你注入到zygote进程时app进程由于是zygote fork来的会继承环境
3. call_common_function 的 api 已说明非常清楚, kCFAddSoinfoToGlobal 将一个模块变为全局模块, kCFCallManualRelink 手动重链接库,加载时机较晚则需要调用 kCFCallManualRelink

**Comment by fuqiangleon** [comment]
1. - 复制导出头文件(源码在 cpp 目录下的 export 目录)到 Hook 模块
2. - 实现linker_export.h中的 fake_load_library_init 导出函数
3. - 调用各种实现方法，查看linker_export.h中的 RemoteInvokeInterface 定义
4. - 正常编写Hook方法如: open，dlopen，dlsym方法等等，方法必须被导出
5. - Hook模块区分Android7.0以下(无命名空间，soinfo handle)，Android7.0及以上(有命名空间，soinfo handle)

根据hook模块的说明，似乎我们自己实现的proxyso 不能用，关于hook模块的开发和使用，能给详细说明下吗？谢谢。

**Comment by sanfengAndroid** [comment]
你可以先实现一个非常简单的例子,看看能否成功然后再实现复杂的功能,具体参考可以见 FakeXposed 这个项目

**Comment by fuqiangleon** [comment]
可以付费请您提供开发支持吗？

**Comment by sanfengAndroid** [comment]
不行

**Comment by fuqiangleon** [comment]
@sanfengAndroid 集成报错如下
![image](https://user-images.githubusercontent.com/1288399/117388280-12d82680-af1d-11eb-8648-1c7b1d391728.png)

**Comment by sanfengAndroid** [comment]
你是用的release-1.0的那个版本吗

**Comment by fuqiangleon** [comment]
是的，github 里的分布版本

**Comment by fuqiangleon** [comment]
fake-linker-v1.0-bin.zip

**Comment by sanfengAndroid** [comment]
那个已经比较旧了,加q群 1042999608 向我发消息

**Comment by fuqiangleon** [comment]
> 1042999608

需要验证 公众号的名字是？

**Comment by sanfengAndroid** [comment]
sanfengAndroid逆向安全

**Comment by fuqiangleon** [comment]
3q
