### ISSUE TITLE
这个项目，必须要配合 fakexposd 才能使用吗，自身没法运行吗？

### ISSUE THREAD

**Issue by thouger** [sanfengAndroid/fake-linker#6]
这个项目中里有两个子项目，都没介绍是什么作用，我运行了 emulator-testapp，其功能没法使用，缺少libfakelinker-test64.so文件，我把 so 复制过去了，还是导致后续一系列连续问题，比如找不到 native 函数等等。
    第二个项目也是没有一点的功能的，因为它的 maintivity 
```
package com.sanfengandroid.fakelinker.test

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }
}

```
只有这么一点内容，运行了也是空白，我观察了它项目里有个 test 文件夹，试图编译：
```
mkdir build
cd build
cmake ../..
make
```
最后还是报错`Could not find a package configuration file provided by "googletest" with`
readme 上它只有结合 fakexposed 上运行，但是fakexposed我也是一堆的报错修复也修复不了

**Comment by thouger** [comment]
研究了很久，发现这种是可以调用的
```
import com.sanfengandroid.fakelinker.FakeLinker
FakeLinker.nativeOffset();
```

**Comment by thouger** [comment]
而且这个项目真的实现了`对外提供基于 LD_PRELOAD 模式加载 PLT hook 模块和各种操作 soinfo、namespace的功能`吗，我全局搜索代码也未能搜到相关函数，对这个项目存在好多疑问，这个项目真正能用的功能是哪一些

**Comment by beichenzhizuoshi** [comment]
所有功能都是可以使用的,并且main最新提交开启了静态库和动态库支持,可以集成到其它项目中,帮助查看[文档](https://github.com/sanfengAndroid/fake-linker/blob/main/README_CN.md),具体的编译可以参考[android.yml](https://github.com/sanfengAndroid/fake-linker/blob/main/.github/workflows/android.yml)是使用gradlew来编译的,因为要依赖一些测试库,如果直接使用cmake需要自己安装并配置googletest和junit-gtest的查找路径
```gradle
dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.test.ext:junit-gtest:1.0.0-alpha02'
    implementation 'com.android.ndk.thirdparty:googletest:1.11.0-beta-1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
```
其它两个模块你不需要关系,核心都在 `library` 模块中,导入`Android Studio`中配置 [local.properties.sample](https://github.com/sanfengAndroid/fake-linker/blob/main/local.properties.sample) 重命名为 `local.properties` 然后编译即可,最简单的直接去[actions](https://github.com/sanfengAndroid/fake-linker/actions/) 下载获取最新生成产物里面的`aar`包导入到项目,后续我再把静态库也打包进去,自己项目集成直接调用 [FakeLinker.initFakeLinker](https://github.com/sanfengAndroid/fake-linker/blob/main/src/main/java/com/sanfengandroid/fakelinker/FakeLinker.java) 初始化加载自己的 `hook` 模块即可,静态库使用目前可以修改发布本地位置下面的 `url = "file://E:/maven-local/repo" ` 然后通过配置本地仓库导入 https://github.com/sanfengAndroid/fake-linker/blob/9821bd186eeebe7cbbea99985e5120efaef171ca/library/build.gradle#L92-L111

**Comment by sanfengAndroid** [comment]
所有功能都是可以使用的,并且可以独立使用不依赖fakexposed,main最新提交开启了静态库和动态库支持,可以集成到其它项目中,帮助查看[文档](https://github.com/sanfengAndroid/fake-linker/blob/main/README_CN.md),具体的编译可以参考[android.yml](https://github.com/sanfengAndroid/fake-linker/blob/main/.github/workflows/android.yml)是使用gradlew来编译的,因为要依赖一些测试库,如果直接使用cmake需要自己安装并配置googletest和junit-gtest的查找路径
```gradle
dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.test.ext:junit-gtest:1.0.0-alpha02'
    implementation 'com.android.ndk.thirdparty:googletest:1.11.0-beta-1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}
```
其它两个模块你不需要关系,核心都在 `library` 模块中,导入`Android Studio`中配置 [local.properties.sample](https://github.com/sanfengAndroid/fake-linker/blob/main/local.properties.sample) 重命名为 `local.properties` 然后编译即可,最简单的直接去[actions](https://github.com/sanfengAndroid/fake-linker/actions/) 下载获取最新生成产物里面的`aar`包导入到项目,后续我再把静态库也打包进去,自己项目集成直接调用 [FakeLinker.initFakeLinker](https://github.com/sanfengAndroid/fake-linker/blob/main/src/main/java/com/sanfengandroid/fakelinker/FakeLinker.java) 初始化加载自己的 `hook` 模块即可,静态库使用目前可以修改发布本地位置下面的 `url = "file://E:/maven-local/repo" ` 然后通过配置本地仓库导入 https://github.com/sanfengAndroid/fake-linker/blob/9821bd186eeebe7cbbea99985e5120efaef171ca/library/build.gradle#L92-L111

**Comment by sanfengAndroid** [comment]
New version released and updated documentation
